### ISSUE TITLE
Getting Error - while run application

### ISSUE THREAD

**Issue by vimalesan** [RisingStack/graphql-server#1]
My node version - v0.12.6

![screen shot 2015-07-08 at 3 37 03 pm](https://cloud.githubusercontent.com/assets/4891156/8567941/0f9be5f4-2587-11e5-8bf4-ef493f0c458a.png)

**Comment by clearjs** [comment]
Either use `iojs` instead of `node` or invoke it with `--harmony` or `--harmony_generators` flag to enable generators.

**Comment by hekike** [comment]
@clearjs it's seems to be that your node version doesn't support generators. But I see from the commented flags that you already realised it. I'm using the latest `iojs` if it helps.

**Comment by hekike** [comment]
@clearjs ahh sry. You just answered to @vimalesan. I missed that. Thanks for the help!

**Comment by clearjs** [comment]
No problem. By the way, adding `--harmony` to `package.json` would solve this issue for everybody else regardless of whether they use `node` or `iojs`. In `iojs` that would enable some newer features, which I assume isn't a problem. Right now instructions in the readme only work for `iojs`.

**Comment by hekike** [comment]
@clearjs thanks for your help. I added it!

**Comment by HoraceShmorace** [comment]
This is still happening.
```
macbook:graphql-server 1337i$ node --harmony src/server/index.js

/Users/1337i/Projects/graphql-server/node_modules/koa/lib/application.js:179
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/1337i/Projects/graphql-server/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/1337i/Projects/graphql-server/src/server/server.js:5:12)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/1337i/Projects/graphql-server/node_modules/babel-core/lib/api/register/node.js:199:5)
macbook:graphql-server 1337i$ 
```
